@Host = http://localhost:5153

POST {{Host}}/auth/register

POST {{Host}}/auth/login

POST {{Host}}/auth/refresh

GET {{Host}}/space-groups

POST {{Host}}/space-groups

GET {{Host}}/space-groups/{id}

PUT {{Host}}/space-groups/{id}

DELETE {{Host}}/space-groups/{id}

GET {{Host}}/space-groups/{id}/spaces

POST {{Host}}/space-groups/{id}/spaces

GET {{Host}}/spaces/{id}

PUT {{Host}}/spaces/{id}

DELETE {{Host}}/spaces/{id}

PATCH {{Host}}/spaces/{id}/order

PUT {{Host}}/spaces/{id}/background-image

GET {{Host}}/spaces/{id}/breaker-groups

POST {{Host}}/spaces/{id}/breaker-groups

GET {{Host}}/spaces/{id}/devices

POST {{Host}}/spaces/{id}/devices

GET {{Host}}/breaker-groups/{id}

PUT {{Host}}/breaker-groups/{id}

DELETE {{Host}}/breaker-groups/{id}

PUT {{Host}}/breaker-groups/{id}/position

GET {{Host}}/breaker-groups/{id}/breakers

POST {{Host}}/breaker-groups/{id}/breakers

GET {{Host}}/breakers/{id}

GET {{Host}}/breakers/{id}/downstream

PUT {{Host}}/breakers/{id}

DELETE {{Host}}/breakers/{id}

PATCH {{Host}}/breakers/{id}/order

PATCH {{Host}}/breakers/{id}/upstream

GET {{Host}}/devices/{id}

PUT {{Host}}/devices/{id}

DELETE {{Host}}/devices/{id}

PUT {{Host}}/devices/{id}/position

GET {{Host}}/devices/{id}/upstream

GET {{Host}}/devices/{id}/breakers

POST {{Host}}/devices/{id}/breakers

DELETE {{Host}}/devices/{id}/breakers/{breakerId}

###
