﻿// <auto-generated />
using System;
using Acrocuit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acrocuit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913005336_ReplaceCascadeWithTriggers")]
    partial class ReplaceCascadeWithTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acrocuit.Models.Breaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakerGroupId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SpaceGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("UpstreamBreakerId")
                        .HasColumnType("int")
                        .HasColumnName("UpstreamBreaker");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "BreakerGroupId")
                        .HasName("UQ_Breaker_Id_BreakerGroupId");

                    b.HasIndex("BreakerGroupId")
                        .HasDatabaseName("IX_Breaker_BreakerGroupId");

                    b.HasIndex("UpstreamBreakerId")
                        .HasDatabaseName("IX_Breaker_UpstreamBreaker");

                    b.HasIndex("BreakerGroupId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_BreakerGroup_Order");

                    b.HasIndex("BreakerGroupId", "SpaceGroupId");

                    b.ToTable("Breaker", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Breaker_NotSelfUpstream", "[UpstreamBreaker] IS NULL OR [UpstreamBreaker] <> [Id]");
                        });
                });

            modelBuilder.Entity("Acrocuit.Models.BreakerGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SpaceGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SpaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "SpaceGroupId")
                        .HasName("UQ_BreakerGroup_Id_SpaceGroupId");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("IX_BreakerGroup_SpaceId");

                    b.HasIndex("SpaceId", "SpaceGroupId");

                    b.ToTable("BreakerGroup", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.BreakerGroupPos", b =>
                {
                    b.Property<int>("BreakerGroupId")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.HasKey("BreakerGroupId");

                    b.ToTable("BreakerGroupPos", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SpaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("IX_Device_SpaceId");

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.DeviceBreaker", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("BreakerId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId", "BreakerId")
                        .HasName("PK_DeviceBreaker");

                    b.HasIndex("BreakerId")
                        .HasDatabaseName("IX_DeviceBreaker_BreakerId");

                    b.ToTable("DeviceBreaker", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.DevicePos", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("DevicePos", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.Space", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BackgroundImageUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SpaceGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "SpaceGroupId")
                        .HasName("UQ_Space_Id_SpaceGroupId");

                    b.HasIndex("SpaceGroupId")
                        .HasDatabaseName("IX_Space_SpaceGroupId");

                    b.HasIndex("SpaceGroupId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_SpaceGroup_Order");

                    b.ToTable("Space", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.SpaceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SpaceGroup", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.SpaceGroupOwner", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SpaceGroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SpaceGroupId")
                        .HasName("PK_SpaceGroupOwner");

                    b.HasIndex("SpaceGroupId");

                    b.ToTable("SpaceGroupOwner", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Username");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.UserSecret", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.HasKey("UserId");

                    b.ToTable("UserSecret", (string)null);
                });

            modelBuilder.Entity("Acrocuit.Models.Breaker", b =>
                {
                    b.HasOne("Acrocuit.Models.Breaker", "UpstreamBreaker")
                        .WithMany("DownstreamBreakers")
                        .HasForeignKey("UpstreamBreakerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Breaker_UpstreamBreaker");

                    b.HasOne("Acrocuit.Models.BreakerGroup", "BreakerGroup")
                        .WithMany("Breakers")
                        .HasForeignKey("BreakerGroupId", "SpaceGroupId")
                        .HasPrincipalKey("Id", "SpaceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Breaker_BreakerGroup");

                    b.Navigation("BreakerGroup");

                    b.Navigation("UpstreamBreaker");
                });

            modelBuilder.Entity("Acrocuit.Models.BreakerGroup", b =>
                {
                    b.HasOne("Acrocuit.Models.Space", "Space")
                        .WithMany("BreakerGroups")
                        .HasForeignKey("SpaceId", "SpaceGroupId")
                        .HasPrincipalKey("Id", "SpaceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BreakerGroup_Space");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Acrocuit.Models.BreakerGroupPos", b =>
                {
                    b.HasOne("Acrocuit.Models.BreakerGroup", "BreakerGroup")
                        .WithOne("Pos")
                        .HasForeignKey("Acrocuit.Models.BreakerGroupPos", "BreakerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreakerGroup");
                });

            modelBuilder.Entity("Acrocuit.Models.Device", b =>
                {
                    b.HasOne("Acrocuit.Models.Space", "Space")
                        .WithMany("Devices")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Device_Space");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Acrocuit.Models.DeviceBreaker", b =>
                {
                    b.HasOne("Acrocuit.Models.Breaker", "Breaker")
                        .WithMany("Devices")
                        .HasForeignKey("BreakerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceBreaker_Breaker");

                    b.HasOne("Acrocuit.Models.Device", "Device")
                        .WithMany("Breakers")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceBreaker_Device");

                    b.Navigation("Breaker");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Acrocuit.Models.DevicePos", b =>
                {
                    b.HasOne("Acrocuit.Models.Device", "Device")
                        .WithOne("Pos")
                        .HasForeignKey("Acrocuit.Models.DevicePos", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Acrocuit.Models.Space", b =>
                {
                    b.HasOne("Acrocuit.Models.SpaceGroup", "SpaceGroup")
                        .WithMany("Spaces")
                        .HasForeignKey("SpaceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Space_SpaceGroup");

                    b.Navigation("SpaceGroup");
                });

            modelBuilder.Entity("Acrocuit.Models.SpaceGroupOwner", b =>
                {
                    b.HasOne("Acrocuit.Models.SpaceGroup", "SpaceGroup")
                        .WithMany("Owners")
                        .HasForeignKey("SpaceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpaceGroupOwner_SpaceGroup");

                    b.HasOne("Acrocuit.Models.User", "User")
                        .WithMany("OwnedSpaceGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpaceGroupOwner_User");

                    b.Navigation("SpaceGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Acrocuit.Models.UserSecret", b =>
                {
                    b.HasOne("Acrocuit.Models.User", "User")
                        .WithOne("Secret")
                        .HasForeignKey("Acrocuit.Models.UserSecret", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Acrocuit.Models.Breaker", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("DownstreamBreakers");
                });

            modelBuilder.Entity("Acrocuit.Models.BreakerGroup", b =>
                {
                    b.Navigation("Breakers");

                    b.Navigation("Pos");
                });

            modelBuilder.Entity("Acrocuit.Models.Device", b =>
                {
                    b.Navigation("Breakers");

                    b.Navigation("Pos");
                });

            modelBuilder.Entity("Acrocuit.Models.Space", b =>
                {
                    b.Navigation("BreakerGroups");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Acrocuit.Models.SpaceGroup", b =>
                {
                    b.Navigation("Owners");

                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("Acrocuit.Models.User", b =>
                {
                    b.Navigation("OwnedSpaceGroups");

                    b.Navigation("Secret");
                });
#pragma warning restore 612, 618
        }
    }
}
