server {
    listen 80;
    client_max_body_size 11m;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $corvauth http://corvauth:80;
    set $app http://app:8080;

    location /auth/ {
        rewrite ^/auth/(.*)$ /$1 break;
        proxy_pass $corvauth;
        proxy_set_header Host $http_host;
    }

    location = /_verify {
        internal;
        proxy_pass $corvauth/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
    }

    location /api/ {
        auth_request /_verify;
        auth_request_set $identity $upstream_http_x_forwarded_identity;

        proxy_set_header X-Forwarded-Identity $identity;
        proxy_set_header X-Forwarded-User-Email "";
        proxy_pass $app;
    }

    location / {
        proxy_set_header X-Forwarded-Identity "";
        proxy_set_header X-Forwarded-User-Email "";
        proxy_pass $app;
    }
}
